### ISSUE TITLE
Cannot compile typed context: The type name Int32' does not exist in the type LinqToVfpLinqPadSystem

### ISSUE THREAD

**Issue by spottedmahn** [tombrothers/LINQtoVFP#1]
When I tried to load my DBC file I'm getting:

>Error. Exception - Cannot compile typed context: The type name Int32' does not exist in the type LinqToVfpLinqPadSystem (line 3801)

![image](https://user-images.githubusercontent.com/14079228/54686869-a3aad880-4af0-11e9-90c6-9f4c06ad16ef.png)

How do I debug this further?  Thoughts? 💭

**Comment by spottedmahn** [comment]
>5.36.03 2019-03-20T09:12:56.7535495-04:00 Custom Data Context Driver - 
Exception: Cannot compile typed context: The type name 'Int32' does not exist in the type 'LinqToVfpLinqPad.System' (line 3801)
   at LinqToVfpLinqPadDriver.Schema.SchemaBuilder.BuildAssembly(String code, AssemblyName name)
   at LinqToVfpLinqPadDriver.Schema.SchemaBuilder.GetSchemaAndBuildAssembly(IConnectionInfo connectionInfo, AssemblyName name, String& nameSpace, String& typeName)
   at LinqToVfpLinqPadDriver.VfpDynamicDataContextDriver.GetSchemaAndBuildAssembly(IConnectionInfo connectionInfo, AssemblyName assemblyToBuild, String& nameSpace, String& typeName)
   at LINQPad.SchemaBuilder.GetSchemaAndBuildAssembly(String repositoryData, AssemblyName assemblyToBuild, String& nameSpace, String& typeName, Boolean allowOneToOne, IDictionary`2& sessionData, DataContextCallbackManager cm)

**Comment by tombrothers** [comment]
I'm not able to reproduce this problem.

Here are the steps that you’d need to debug this issue:

- Update the LinqToVfpLinqPadDriver project’s post build event to point to your AppData path.
- Modify the source code to include a call “System.Diagnostics.Debugger.Launch();” where you would expect to put a breakpoint.
- Build the project.

**Comment by spottedmahn** [comment]
Thanks! 👍

Looks like the problem is there is table called `System`

![image](https://user-images.githubusercontent.com/14079228/54925813-72ae1780-4ee5-11e9-9528-3ac913621b07.png)

Any thoughts a fix?

**Comment by spottedmahn** [comment]
I'm guessing `global::` is the fix?

Reference: https://stackoverflow.com/questions/15022441/what-is-global

**Comment by spottedmahn** [comment]
Nvm, found it!

![image](https://user-images.githubusercontent.com/14079228/54926583-00d6cd80-4ee7-11e9-947e-1a93d60b76b0.png)

I'll submit a PR...

Thanks for creating this driver!! I 💖 LinqPad

**Comment by spottedmahn** [comment]
Success 😊

![image](https://user-images.githubusercontent.com/14079228/54926735-43000f00-4ee7-11e9-918c-508e4d399f44.png)
